src/kernel.c

Before the faults would show up as an invalid string, now they work
example code:
```
void operatorControl() {
printf("Hello, World!\n");
printf("I have a good idea, lets cause a segfault!\n");
delay(5000);
volatile int x = *((int*) 0xFFFFFFFF) = 69;
delay(5000);
printf("I survived! %d\n", x);
while (1) {
delay(20);
}
}
```
before:
```
Powered by PROS 2.11.0
PROS (C)2011-2014 Purdue ACM SIGBOTS
This program has ABSOLUTELY NO WARRANTY, not even an implied
warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Hello, World!
I have a good idea, lets cause a segfault!
The VEX Cortex has stopped working!
Error cause:
```
after:
```
Powered by PROS 2.11.0
PROS (C)2011-2014 Purdue ACM SIGBOTS
This program has ABSOLUTELY NO WARRANTY, not even an implied
warranty of MERCHANTABILITY or …
```

Fix broken fault reporting

---

README.md

I feel like I keep doing this, but for some reason attempting to hotlink our repos à la `purduesigbots/pros` doesn't work [anymore], so I'm changing them to absolute links for absolute consistency

Fix links at the bottom of README (again)

---

Makefile
include/API.h
src/supervisor.c

This needs testing. I had a dubious rig set up, but then I lost the toolchain. Oh 🐳.

Add standalone operational mode

---

.github/CONTRIBUTING.md
README.md

Add information about our various repositories in the contribution guidelines.
These can be basically dropped in to the same file in our other repositories.
Seeking input on my examples of issues that should be opened in each repo, as I think they're a little lame.

GitHub docs updates

---

include/pros/apix.h
include/rtos/FreeRTOSConfig.h
src/rtos/task_notify_when_deleting.c
src/system/rtos_hooks.c

- Increments `configNUM_THREAD_LOCAL_STORAGE_POINTERS` again
- Adds another linked list to thread local storage that will keep track of the tasks to whose death events `task_to_notify` is subscribed
- When a task dies, the `task_delete_hook` now iterates through the task's list of subscriptions and removes references to itself from the subscriptions' lists of subscribers
Previously, the case in which `task_to_notify` dies before `target_task` was undefined behavior, because `target_task` would attempt to notify `task_to_notify` even if it's already been cleaned up. The naive solution of checking the `task_to_notify`'s state directly would not have worked because in certain cases (as with the competition tasks), the TCB can be reused.
More information regarding the motivation behind this …

🐛 Refactor task_notify_when_deleting to support task_to_notify dying before target_task

---

src/display/llemu.c

Someone wrote LLEMU overnight and didn't sleep. So he forgot to add `nullcheck` in method `lcd_read_buttons`.
Add it.
Closes #106

🐛 Add LLEMU read buttons nullcheck

---

azure-pipelines.yml
version.py

```
make template
make
```
would cause the version to be updated to a dirty commit version, which would then get set as the build number (despite being a commit build)
This change does
```
make template
(Update Build number)
make
```
So that we don't see a dirty version

👷‍♂️ Re-order make execution after updating build number

---

version.py

Need a "." between build number and commit, not a plus
Use non-tagged templates built by Azure
purduesigbots/pros-cli#66
purduesigbots/pros-cli#64

🤦‍♀️ Dot between build ID and commit on Azure Pipelines

---

common.mk

Remove timestamp compilation from cold ELF
If you have multiple projects with the same set of libraries (e.g. same hash) but the cold ELF was compiled at different times, then the CRCs won't match even though the relevant symbols are equivalent.
- Validated by me and @jcgrif

Don't include timestamp in cold image

---

common.mk

Changes COLD_LIBRARIES from a simply expanded variable to a recursive one so that compilation with user-defined libraries still works.
Went to add a template generated from the latest code on develop to a project that uses a user-created library (the BLRS 15" robot), and the project failed to compile with the following error: 
```
bayle@pop-os:~/Documents/git/forkner$ make
Creating cold package with libpros,okapilib,libforkner [ERRORS]
/usr/bin/../lib/gcc/arm-none-eabi/7.3.1/../../../../arm-none-eabi/bin/ld: cannot find ./bin/libforkner.a: No such file or directory
collect2: error: ld returned 1 exit status
common.mk:201: recipe for target 'bin/cold.package.elf' failed
make: *** [bin/cold.package.elf] Error 1
```
I believe the bug was introduced in #121.
All tests are done with the BLRS …

🐛 Fix COLD_LIBRARIES variable assignment

---

common.mk

Someone doesn't want to waste his time. So he adds this code to make compile-job faster. The compiler now doesn't need to remove and create `temp.log` every time it compiles a file. 
Add it.
close #103

✨ Improve Makefile compile speed

---

include/pros/motors.h
src/devices/vdml_motors.c

Fix incorrect port type in some motor functions
They were different from everywhere else with seemingly no reason.

Fix incorrect port type

---

include/api.h
include/pros/apix.h
include/pros/serial.h
include/pros/serial.hpp
src/devices/vdml_serial.c
src/devices/vdml_serial.cpp
src/system/dev/dev_driver.c
src/tests/generic_serial.cpp
src/tests/generic_serial_file.cpp

- Add alternate generic serial API
- Fix filesystem generic serial driver
The alternate generic serial API was added for users who want a lower level serial API. The generic serial filesystem driver was broken so it was fixed and implemented using the new API so the VEXos functions are only called in one place.

Add alternate generic serial API and fix generic serial filesystem driver

---

src/devices/vdml_vision.c

- Update vision_read_by_sig to properly transform coordinates and respect array boundaries
- We weren't properly respecting array boundaries on read_by_sig, now we are
I noticed this by code inspection a while back but no one had reported an issue, so I never submitted a PR.
Close #118

🐛 Update vision_read_by_sig to be less funky

---

src/system/cpp_support.cpp
src/system/mlock.c
src/system/newlib_stubs.c

arm-none-eabi-8-2019-q3-update was released, which finally bumped arm-none-eabi-gcc to 8.3 officially, so we started running into the missing `__sync_synchronize` symbol as well. This PR fixes that, as well as a new multiple definitions issue (`__malloc_lock`/`unlock`).
The solution to the `__sync_synchronize` issue is described in https://github.com/purduesigbots/pros/issues/153#issuecomment-519335375.
`__malloc_lock` and `__malloc_unlock` were moved from src/system/newlib_stubs.c to their own file src/system/mlock.c, which [apparently is how newlib determines overrides](http://sourceware-org.1504.n7.nabble.com/malloc-lock-tp179955p179956.html).
Since the latest official version of the toolchain now includes 8.3, we can't really just tell people that they should use the official one …

🚨 Make things work with GCC 8.3

---

template-Makefile

This PR enables hot/cold by default.
Wireless uploading is optimized on other platforms by default. PROS should match this behavior.

🔧 Enable hot/cold by default

---

VSCode.md
include/pros/adi.h
include/pros/adi.hpp
include/vdml/registry.h
include/vdml/vdml.h
src/devices/vdml_adi.c
src/devices/vdml_adi.cpp

The ADI C API has been modified to be more self consistent. `adi_encoder_t`, `adi_ultrasonic_t` and `adi_gyro_t` now represent the user supplied port (1 through 8 instead of 0 through 7) so that functions like `adi_encoder_get` can accept either the return value from the device initialization or a user supplied port number. `errno` is now properly set during ADI port validation failures and other small bugs were fixed. The ADI C++ destructor was changed to not clear the port configuration to make it similar to other PROS API's where multiple instances can be created and destroyed without side effects.
Some functionality did not match what a user would expect and in some cases did not match the PROS documentation.
closes #115 
closes #148 
closes #149

🐛 Fix multiple ADI bugs and inconsistencies

---

include/pros/llemu.h

This PR pushes `ignored "-Wignored-qualifiers"` when including the LVGL headers.
The LVGL headers cause a lot of noise via compiler warnings. This PR silences those warnings.

🤫 Suppress ignored qualifiers when including lvgl

---

include/pros/rtos.hpp
src/rtos/rtos.cpp

Adds an alternate constructor to pros::Task that omits task priority and stack depth, while keeping the task function, parameter, and name.
Modifying priority and stack depth is not always used, however users such as myself like to always have task names set. This alternate constructor will assume defaults without needing them specified.
There is no reason why this should not work, as it just passing to task_create, but any tests that apply to standard tasks could be easily adapted to ensure this works.

🚸 Add alternate constructor for pros::Task

---

azure-pipelines.yml

the PPA was hanging, and it installs an old version anyway

💚 Update toolchain installation for azure

---

src/main.cpp

Fixes a regression introduced in #152 whereby the default LLEMU initialization code was removed.
Code in `opcontrol()` that displays information to LLEMU was not removed, so users will (reasonably) expect the code to Just Work™ out of the box.
closes #164

🐛 Add default LLEMU init code back to main.cpp

---

src/system/cpp_support.cpp

When exceptions are thrown, PROS catches them and prints them to the screen.
However, long messages are often cut short and unreadable.
With this PR, exceptions caught by PROS will be printed to the terminal as well as to the V5 Screen.
I have also separated the screen printing commands to try and fit the most of the error message as possible.
After testing this PR, it does not seem to be printing to the terminal.
This might be due to the order of initialization or something, idk.

🚸 Implement exception logging to terminal

---

common.mk

Automatically include any firmware/*.mk scripts in Make system to allow
templates to modify build process (e.g. add extra flags or
dependencies).
A library wishes to dynamically generate a C file at Make time based on some text file and include in project's binary. There is currently no support for this. With this modification, library author creates a firmware/mylibrary.mk file which adds the corresponding variable modifications and rules to ensure the C file is generated and compiled as part of the user's project.

✨Add support for extra Make scripts

---

include/pros/rtos.hpp

Add two constructors to `Task`, analogous to the existing ones, to enable construction from any `void()` callable (including lambdas with captures).
This should improve ease of use and intuitive interface for creating Tasks. It is also a C++-idiomatic approach.
Simple tests can be constructed using C++ lambdas with captures. Example code:
```
std::unique_ptr<int> data{new int(7)};
pros::Task task{[=] {
pros::delay(1000);
std::cout << *data << std::endl;
}};
```

🚸 Allow tasks to be constructed from any void() callable

---

include/pros/misc.h
include/pros/misc.hpp
src/devices/controller.c

Through some testing I determined that `vexControllerTextSet` returns 0 if it fails to send data to the controller (such as when the user sends updates quicker then every 50ms or if the controller is unplugged). Using this, `controller_set_text`, `controller_print` and `controller_clear_line` have been updated to return `PROS_ERR` on failure setting `errno` to `EAGAIN`.
I also updated `controller_clear` to block for the required 110ms for it to work. I would probably recommend either deprecating this function or implementing a more complex controller system that queues updates and pushes to each line in a cyclic pattern every 50ms, but that's another matter.
Would probably be nice to give the user feedback on whether their calls succeed instead of silently failing.
If someone could test …

✨ Provide error if updates are sent too quickly to the controller or if it is not connected

---

src/display/lv_misc/lv_task.c

Within lv_task, we were using a non atomic swap as a mutex. This changes these to be volatile/atomic where necessary. I also noticed a path where said "mutex" could be abandoned, so that's fixed as well.
Non deterministic races aren't fun.
Pointed out in https://github.com/purduesigbots/pros/issues/90#issuecomment-545628430

🐛 Fix race and an abandoned mutex

---

src/devices/controller.c

Fixes clearing both the full screen and a single line.
With this working:
`master.print(0, 0, "abcdefghijklmnopq");`
`pros::delay(50);`
`master.print(1, 0, "abcdefghijklmno");`
`pros::delay(50);`
`master.print(2,0,strerror(errno));`
`pros::delay(50);`
`master.clear();`
`pros::delay(3000);`
`master.print(0, 0, "abcdefghijklmnopq");`
`pros::delay(50);`
`master.clear_line(0);`

🐛 Fix clearing controller LCD

---

include/pros/adi.h
include/pros/llemu.h
include/pros/rtos.h

Some header files for the C API were missing include directives for `<stdbool.h>`. This is only evident when they are included directly, rather than via `<api.h>` or `<apix.h>`. In this case, it results in a compiler error, as the then-undefined `bool` type is used in the header; the user is forced to include `<stdbool.h>` themselves before including the particular header.
General good practice of including everything that the header depends on.
Just make sure it compiles, trivial and non-functional change so I don't expect any issues.

Add missing include directives for <stdbool.h>

---

common.mk

This PR adds `-Wno-psabi` to `WARNFLAGS`.
Many users encounter a warning similar to this, especially when using OkapiLib:
```
parameter passing for argument of type 'std::initializer_list<okapi::Point>' changed in GCC 7.1
```
It causes a lot of unnecessary confusion, so we should ignore it by default.
None.
There is no test plan.

🔇 Stop warnings for GCC 7.1 ABI change

---

common.mk

While working on another pr, I noticed we weren't generating header change tracking files for files with the same name, but different extensions. This reworks generating those based on the full un-compiled names, similar to what we do with object files. 
Some people in discord were also getting confused when a file failed to compile, a could not move error from mv was showing. This also silences that.
Misc makefile cleanup from my changes.
Files only sometimes recompiling isn't fun, though the kernel is likely the only people to hit this.
None

🐛Fix header tracking of duplicate basename files

---

.gitignore
include/api.h
include/pros/apix.h
include/pros/imu.h
include/pros/imu.hpp
src/devices/vdml_imu.c
src/devices/vdml_imu.cpp

Does what it says on the tin-- adds support for the new VEX Inertial Sensor (IMU).
Got at least one person a day asking me where this feature was since VEX announced (and started shipping) the new sensor last week.
Surprisingly none.
- TBD

✨ Add support for VEX Inertial Sensor

---

include/pros/misc.h
include/pros/misc.hpp
src/devices/vdml_usd.c
src/devices/vdml_usd.cpp

Well, I am still thinking about is it a suitable name for namespace and method.
**Namespace**: usd? SDcard? sdcard? or without namespace? (like: `pros::is_usd_installed()`)
**Method**: is_installed? is_inserted? is_mounted? is_connected? is_valid? etc...
Add it
#174 @nathan-moore 
```cpp
while (true) {
pros::lcd::print(2, "Installed? %d", pros::usd::is_installed());
pros::lcd::print(3, "Installed? %d", pros::c::usd_is_installed());
pros::delay(20);
}
}
```

✨ Add SD card detection command

---

include/pros/motors.hpp
include/pros/serial.hpp
include/pros/vision.hpp
src/devices/vdml_motors.cpp
src/devices/vdml_serial.cpp
src/devices/vdml_vision.cpp

Someone(yes, he is me) thinks it is better to have a getter method. So I added `get_port` method in Motor, Vision and Serial classes. It is useful for VEXU team which has more than 16 motors in a robot and messes it up.
Love, yes, it is.
Null
```cpp
pros::Motor the_motor(2);
pros::Serial the_serial(3);
pros::Vision the_vision(4);
while (true) {
pros::lcd::print(2, "The port number is: %d", the_motor.get_port());
pros::lcd::print(3, "The port number is: %d", the_serial.get_port());
pros::lcd::print(4, "The port number is: %d", the_vision.get_port());
pros::delay(20);
}
}
```

✨ Add a new class method: get_port

---

src/system/dev/file_system_stubs.c

Put in some temporary file system stubs to allow people to compile. This will hold us over until #184 is merged, and should reverted as part of that pr.
This allows people using the newest c++ stdlib to use hot cold. Previously they would either need to define the stubs themselves, downgrade gcc, or not use hot/cold.
Contribues to #176

Put in temporary file system stubs

---

src/rtos/tasks.c

The millis() number reset to zero every 1h 11m 34s and 967ms.
According to the source code:
https://github.com/purduesigbots/pros/blob/1e07ae915b38689ae53a9f03cacc8fbbed09dbff/src/rtos/tasks.c#L2050-L2062
Ok, so we are using `uint32_t` and the maximum value is `2^32 = 4294967296`
At the same time. 1h 11m and 35s equal to `71*60*1000+35*1000 = 4295000`
Please pay attention to line 2061, `return xTicks * configTICK_RATE_HZ / 1000;`
That equals to `4295000 * 1000 / 1000` -> `4295000000 / 1000` and 4295000000 > 4294967296
The millis() overflow. 
Running a program for over an hour.
My time
```cpp
while (1) {
pros::lcd::print(6, "Time: %d", pros::millis());
pros::lcd::print(7, "H:%d M:%d S:%d", pros::millis()/1000/60/60,
pros::millis()/1000/60%60,
pros::millis()/1000%60); …
```

🐛 Fix the problem of millis()

---

common.mk

Gnu Make 4.3 broke how we generated spaces. This fixes that.
Fix pros for people who actually keep things updated
fixes #206

🥅 Fix Makefile spaces definition

---

src/system/dev/ser_daemon.c

Properly flush character in serial command buffer if 'p' is accepted and the following character is not.
If you echo back every character that is typed in shell, you will observe that any character following "p" never shows up.

🐛 Properly flush character to user frontend

---

README.md

Change it from https://vexforums.dom/index.php/ which does not exist to https://vexforums.dom/ which is the homepage.

Fix the VEX Forums link

---

include/pros/misc.hpp
src/devices/controller.cpp

Basically what the title says.... it's pretty simple.  I also included std::string into the file because I wasn't really sure if it was included elsewhere but I figured I might as well be safe.
It was annoying me that I had to add .c_str() every time I called set_text();
Also hotel said it was ok :)
uh you can call it and see if it works I guess.  I don't foresee there being any major issues with this change.

Added an std::string overload of Controller::set_text()

---

.gitignore
include/pros/imu.h
include/pros/imu.hpp
src/devices/vdml_imu.c
src/devices/vdml_imu.cpp

Does what it says on the tin. Also adds the IMU data refresh rate setter function.
This will allow us to support the new sensors when they come out. Also people were asking for the IMU part.
N/A

⬆ Upgrade vexOS to 1.0.11

---

src/devices/controller.c

VCS and RMS have had their controller max string sizes at 19 for a while, and PROS also having this wouldn't be too hard of a change. This was done by changing `CONTROLLER_MAX_COLS` under `src/devices/controller.c` to 19.
There was an issue opened by @djava requesting that we do this, but the discussion surround this died pretty suddenly so I decided to open a PR regarding this to restart the conversation
fixes https://github.com/purduesigbots/pros/issues/217

✨Increasing the Max String Size on the Controller Display

---

include/pros/rtos.h
include/pros/rtos.hpp
src/rtos/rtos.cpp
src/rtos/semphr.c

Added a function to allow for deleting a mutex within a c++ context as well as a specific c function in order to fix the possible memory leak.
Currently this code will cause the v5 to freeze to an unrecoverable state after <15 seconds:
`while(true){pros::Mutex{});}`
Some possible issues:
-The function to free memory is called pros::Mutex::free, delete would have been preferable to match the c api but is a reserved word.
-This function cannot be implemented within a destructor because for a mutex to fulfill it's purpose multiple objects with the same memory pointer must exist. This can be done utilizing reference counting but that is a larger change outside the scope of this.
Future improvements
-Adding reference counting to make destruction automatic
-Making free also set the pointer to …

Added mutex_delete functionality

---

include/pros/rtos.hpp
src/rtos/rtos.cpp

Makes pros::Task::notify_take static and pros::Task::operator= stl compliant.
pros::Task::notify_take used to require a task handle to be used but that task handle was never used in the function. With it being static it can now be called without a handle without breaking current user code.
pros::Task::operator= used to return void and this makes it return pros::Task&, a good explanation for why this is better can be found here: [explanation](https://stackoverflow.com/questions/42335200/assignment-operator-overloading-returning-void-versus-returning-reference-param)

pros::Task::notify_take static and pros::Task::operator= stl compliant

---

src/devices/vdml_imu.c

Removed a ERROR_IMU_STILL_CALIBRATING in vdml_imu.c, which doesn't make sense to check if the imu was still calibrating and not return this status.

Removed non-sensical imu calibrating check in imu_get_status

---

common.mk

Remove linking in the compiler provided libc and libm and libsupc++ as its a subset of libc++
Will happily add more.
Note that this fixed some compiler errors when using a very recent version of gcc.

🥅 Remove redundant library links

---

include/pros/adi.h
include/pros/ext_adi.h

This PR adds documentation about the allow ADI ports for an encoder's top wire.
This is currently only documented on the website.

Fix ADI encoder docs missing a comment about allowed top port

---

include/pros/rotation.h

This PR clarifies the return value of `rotation_get_angle`.
This was unclear to me before talking with @HotelCalifornia

🚸 Clarify rotation_get_angle API

---

src/system/dev/file_system_stubs.c

Adds missing File System stubs: symlink, readlink, truncate, fchmod, fchmodat.
Dependencies on these syscalls were added with the gcc-arm-none-eabi-10-2020-q4-major update (in c++20-compliant std::filesystem functions)
Closes #273

👽 Add missing filesystem syscalls

---

include/pros/rtos.h
include/pros/rtos.hpp
src/rtos/tasks.c

Adds `pros::micros()` to return the time since program start in microseconds.
I noticed `pros::millis()` didn't use `vexSystemTimeGet()` but I'm not familiar enough with FreeRTOS to know what it's doing and if that'd be better then wrapping `vexSystemHighResTimeGet()`.
There is currently no sub-millisecond timing. 
Closes #280

 ✨ Add microsecond timing

---

include/pros/apix.h
include/vdml/registry.h
src/devices/registry.c

Move the decelerations of `registry_get_bound_type` and `registry_get_plugged_type` from `registry.h` to `apix.h` to expose them to users.
Currently there is no way for user code to query the bound and plugged status of each port. This is useful to make sure devices are ready to use before they are accessed.

✨ Allow user code to query registry status

---

include/pros/motors.h
include/pros/motors.hpp
src/devices/vdml_motors.cpp

Removed the functionality of pid setting functions and added deprecation warnings to them. The functions included are:
for the c implementation--
`pros::c::motor_set_pos_pid`
`pros::c::motor_set_pos_pid_full`
`pros::c::motor_set_vel_pid`
`pros::c::motor_set_vel_pid_full`
for the C++ implementation--
`pros::Motor::set_pos_pid`
`pros::Motor::set_pos_pid_full`
`pros::Motor::set_vel_pid`
`pros::Motor::set_vel_pid_full`
As stated in #291 motors can be broken using the pid setting functions therefore they should be removed.
closes #291
Unfortunately, I do not have access to a brain, so I tested these functions by calling them in main.cpp in a main() method.
For each method I wrote--
```C++
int main() {
// set_pos_pid
pros::Motor motor(1);
pros::motor_pid_s_t pid = pros::Motor::convert_pid(KF, …
```

🔥 Deprecate PID setting functions

---

include/pros/imu.h
include/pros/imu.hpp
src/devices/vdml_imu.c

The calibration flag is not set immediately after a call to `imu_reset` necessitating user code to add a delay before polling the status of the IMU. By adding a 20 ms delay after calling `vexDeviceImuReset` in `imu_reset`, the calibration flag is correctly set once the function returns.
`imu_get_status` should reflect that the IMU is calibrating immediately upon the return of `imu_reset`.
The delay between `vexDeviceImuReset` and the calibration flag being set was found by running 
```c
void initialize() {
imu_reset(IMU_PORT);
uint32_t start_time = millis();
while (!(imu_get_status(IMU_PORT) & E_IMU_STATUS_CALIBRATING)) {
}
uint32_t delta = millis() - start_time;
FILE* file = fopen("/usd/logging.csv", "a");
char str[100];
sprintf(str, "%d, ", delta);
fputs(str, file);
fclose(file);
}
``` …

✨Added Delay to IMU Reset

---

include/pros/gps.hpp

Fixed borked GPS header guard *(Let's release 3.5.2 asap)

🚸 Fixed GPS HPP Header Guard

---

src/devices/vdml_adi.cpp

Bruh.
Love.
#321 
```cpp
pros::Controller master(pros::E_CONTROLLER_MASTER); 
pros::ADIDigitalOut claw({INTERNAL_ADI_PORT, 'A'}, false);
// jerry::ADIDigitalOut claw('A', false);
// jerry::ADIDigitalOut claw({INTERNAL_ADI_PORT, 'A'}, false);
while (true) {
if (master.get_digital(pros::E_CONTROLLER_DIGITAL_L1))
claw.set_value(true);
else
claw.set_value(false);
pros::delay(10);
}
```

:bug: Bugfix ADI Digital Out constructor

---

include/pros/rtos.h
include/pros/rtos.hpp
src/rtos/rtos.cpp

Added a default constructor for mutex_take that initializes the timeout to TIMEOUT_MAX
users should be able to call pros::Mutex::take with no arguments and have it wait forever
https://github.com/purduesigbots/pros/issues/316
Call Mutex::take with no arguments & see if it doesn't time out.

✨Define mutex_take default instructor

---

firmware/v5-common.ld

`gcc_except_table` was misspelled as `gcc_execpt_table`.
The linking is improper if the exception table is not included properly.

🐛 gcc exception table section name typo

---

src/devices/vdml_ext_adi.c

This PR removes the internal ext_adi_gyro wrapper, and uses claim_port_f properly instead of claim_port_i.
Also adds a validate_type_f for float returns.
Motivation: Unnecessary stack frame removed

🚸Removed internal ext_adi_gyro wrapper

---

src/display/llemu.c

This prevents a segfault that occurs when the LCD on LLEMU is cleared.
closes #338

🐛 Prevent LLEMU Clearing Segfault

---

include/pros/rotation.h
include/pros/rotation.hpp
src/devices/vdml_rotation.c
src/devices/vdml_rotation.cpp

Created a constructor with a block to prevent race conditions. Waits for the sensor initialization to complete to set the reverse flag.
https://www.vexforum.com/t/rotation-sensor-bug-workaround-on-vexos-1-1-0/96577
It builds.

🐛 Fix rotation sensor race condition

---

include/pros/screen.h
include/pros/screen.hpp
src/devices/screen.c
src/devices/screen.cpp

Implemented error catching and handling for the screen class, where if an error is detected (e.g. a mutex isn't able to be taken), the method in question will catch the error, set errno to the proper error, and return PROS_ERR. 
The screen class didn't have any error catching or handling, as such this addition will help users when debugging their code.
closes #328 
While a mutex is taken, run methods from the screen class; if they set errno correctly and return PROS_ERR, then the error handling works fine.

✨Implement Error Handling For Screen

---

azure-pipelines.yml

Since the CI broke on the newest CLI release, we should temporarily retarget the CLI install to 3.2.3 to keep development going.
Of course, this is temporary until issues with the CI are fixed.

🐛Temporarily Retarget CLI install to 3.2.3 for CI

---

include/pros/screen.h
include/pros/screen.hpp

Title, there were some typos on the screen docs w/ this

🐛 Fix instances of prosERR to PROS_ERR on Screen Docs

---

src/system/newlib_stubs.c

Add a stub implementation of the `getentropy` function to the newlib stubs included in libpros.
Currently, if the arm-none-eabi toolchain's libc is too new, it will emit a reference to getentropy, which results in a linker error
Closes https://github.com/purduesigbots/pros/issues/362

🐛Add getentropy to newlib stubs

---

firmware/v5-common.ld
firmware/v5-hot.ld
firmware/v5.ld

Gnu ld 2.38 now uses MEMORY as a keyword, while the pros linker scripts uses it as the name of a region, causing an error during linking that prevents any project from building. This PR contains a simple fix for that by renaming all instances of MEMORY to RAM. 
closes #364

🐛 fix linker script improper use of keyword as region name

---

include/pros/rtos.hpp

Add a new class template, `MutexVar<Var>`, which wraps a mutex and a variable of type `Var`, allowing access to the protected variable only via a `MutexVarLock`, which is a specialized RAII handle representing exclusive access.
This is inspired by and implements the same pattern as [Rust's `Mutex` type](https://doc.rust-lang.org/std/sync/struct.Mutex.html). It provides a means of using the compiler to enforce a contract of exclusive access to a variable via a mutex, rather than relying on the programmer to ensure that they bracket accesses with `take()` and `give()` calls. The RAII pattern also ensures that it is exception-safe.
```cpp
MutexVar<bool> flag{false};
Task([] {
for (int i = 0; i < 100; i++) {
*flag.lock() = true;
delay(10);
}
});
while (true) {
if …
```

✨Add MutexVar

---

include/pros/imu.h

During compilation of the develop-pros-4 branch there are multiple warnings about the doxygen style comment blocks in the `include/imu.h` file such as:
```
In file included from ./include/api.h:55,
from ./include/kapi.h:21,
from src/system/startup.c:18:
./include/pros/imu.h:50:2: warning: multi-line comment [-Wcomment]
50 |  /// Used to indicate that an error state was reached in the imu_get_status function,\
|  ^
```
Doxygen allows for multiple styles of comment blocks so it is better to go with something that does not generate such warnings.
Removing these warnings will allow for more efficient development of pros 4 and replacing the comment block style is a better alternative than suppressing the warnings.
From the [Doxygen Manual](https://www.doxygen.nl/manual/docblocks.html) we have …

Resolve compiler warnings for doxygen comment blocks in imu.h

---

include/pros/imu.h
include/pros/link.h
include/pros/optical.h

Added Simple Names for IMU and Link Enums, were missed while they were in development.

🚸Add Simple Names for IMU and Link Enums

---

include/pros/imu.h
include/pros/imu.hpp
src/devices/vdml_imu.c
src/devices/vdml_imu.cpp

Added an option in the C and C++ API for a calibration function to block while resetting instead of forcing the user to do it every time.
- `pros::c::reset_blocking();`
Added a default parameter to Imu::reset that doesn't block by default, but will block if `.reset(true);` is called.
- `pros::Imu::reset(bool blocking = false);`
Improve the PROS API and its usability
#398 
This should be a short hardware test:

✨Add Blocking Reset Option for IMU

---

include/vdml/vdml.h

Removes redundant port number validation in claim_port, the reason being that it's already done in registry_validate_binding. This is to ensure that 
Although this is a relatively small change, claim_port is used often throughout our code and constantly called as an easy way to retrieve a registry mutex whenever a user needs to interact with the hardware. I'm not sure how much of an optimization it is, but given the sheer amount of times it gets called we might as well remove this double check which I don't think would be optimized out.
Although this change effects every hardware interacting call... testing only one device should be enough since it's just a macro.

🎨 Remove Redundant Port Validation

---

include/pros/screen.h
src/devices/screen.c

Fixed touchbacks causing a prefetch error, as well as fixing the touch status to not hang.
Both features were tested with the following codes:
```C++
pros::screen_touch_status_s_t status;
while(1){
status = pros::c::screen_touch_status();
// Will print various information about the last touch
pros::lcd::print(pros::TEXT_MEDIUM, 1, "Touch Status (Type): %d", status.touch_status);
pros::lcd::print(pros::TEXT_MEDIUM, 2, "Last X: %d", status.x);
pros::lcd::print(pros::TEXT_MEDIUM, 3, "Last Y: %d", status.y);
pros::lcd::print(pros::TEXT_MEDIUM, 4, "Press Count: %d", status.press_count);
pros::lcd::print(pros::TEXT_MEDIUM, 5, "Release Count: %d", status.release_count);
pros::delay(20);
}
}
```
```C++
void changePixel(){
pros::screen_touch_status_s_t status = …
```

🐛 Fix Issues with Screen Touchbacks and Touch Status

---

include/pros/motors.hpp
src/devices/vdml_motors.cpp

Adds missing methods for motor groups.
Adds tare_position and get_position
closes #407

✨Missing Motor Group Methods

---

template-gitignore

Added `.cache/` to .gitignore
This stops a bajillion files appearing in git.

🐛Add `.cache/` to .gitignore to prevent extra files from being committed

---

src/devices/vdml_ext_adi.c

subtracted 1 from smart_port because it needs to be zero-indexed 🙃
I did a lot of testing and I am fairly confident that this is where the issue is. It's a problem with different indexing systems for smart ports. I started by testing addrled functions in VEXcode by using the SDK directly. The working code there looked like this. 
```cpp
#include "vex.h"
vex::brain       Brain;
// Declaration for SDK function for setting addrled. written by james, i just copied it
extern "C"  int32_t  vexAdiAddrLedSet( uint32_t index, uint32_t port, uint32_t *pData, uint32_t nOffset, uint32_t nLength, uint32_t options );
int main() {  
// Create a buffer 8 long, all one color
uint32_t maxled = 8;
uint32_t ledbuffer[64];
for(int i = 0;i<maxled;i++){
ledbuffer[i] = 0xB00B69;
}
// Use sdk calls to configure …
```

fix ext_adi_led_set and ext_adi_led_set_pixel

---

include/pros/motors.hpp
src/devices/vdml_motors.cpp

Change Motor constructors' port param from uint8_t to int8_t
Add functionality for users to input a negative port into Motor constructors to reverse motors at that port. 
See if motors spin in reverse after passing in a negative port parameter.

✨ Add Reverseable Motors to Default API

---

include/pros/motors.hpp
src/devices/vdml_motors.cpp

Added functionality for MotorGroups to be treated more like arrays than classes. With these changes the user should be able to index a MotorGroup similar to an array, and get its size with a size() method. This should allow MotorGroups to be looped through.
#450 
Requires hardware testing. Asked to add this PR ASAP in order to keep ahead on schedule. Will hardware test and add information about that here when completed.

✨Added functionality for size() and [] operator

---

src/devices/vdml_adi.cpp

Says what it does in the title
- Try using this constructor and initializing/using a LED strip from the lab and seeing if it works. 
Props to @SylvieMayer for assisting in finding this.

🐛 Fix bug with LED non-extended constructor

---

src/system/startup.c

This is a simple fix that makes display_initilialize() a weak symbol so that the implementation in the liblvgl repo can be used. 
The default implementation does not do anything. If the liblvgl template is present, the implementation in that template will be used.

🐛Make display_initialize() a weak symbol for the liblvgl template

---

include/main.h

Convenient was misspelled as "convienent."
Changed the word "convienent" to convenient.
To make the document clearer and more professional.

Correct misspelled word

---

Makefile
common.mk

This PR changes the makefiles to use the command `pros` instead of `prosv5`
When permissions issues arise on *nix systems, users have to chmod `pros` since that's what people typically use and `prosv5` since that is what the build system uses. This change would remove the need to set permissions on the latter. Additionally, we do not support the cortex anymore, so there is little reason for the build system to use `prosv5`
I have tested the various commands regarding the make command, and they still work on my system.

⬆️ Change makefiles to use 'pros' instead of 'prosv5'

---

include/pros/optical.h
include/pros/optical.hpp
src/devices/vdml_optical.c
src/devices/vdml_optical.cpp

Added Integration Time Setting/Getting to Optical, C and C++, bounds are 712 ms max and 3 ms min. 
#473

✨ Add Integration Time Setting/Getting to Optical

---

include/pros/motors.hpp
src/devices/vdml_motors.cpp

Adds the at() operator to the Motor_Groups. Throws an error if the bozo attempts to go out of ranges. 
Issues with smart pointers make the process of using the [] operator a headache. This method should offer a simple solution while being similar to C++ syntax. 
#494 
Will test on simple program that controls multiple motors and I will check if I can use them when using a smart pointer. Will post here with update on proper test.

✨ PROS 3.8: Add "at()" Method To Motor Groups

---

common.mk
include/api.h
include/pros/adi.hpp
src/devices/vdml_adi.cpp
src/main.cpp
src/tests/pnuematics.cpp

Add the Pneumatics Class. Functions in this class are extend(), retract(), toggle(), and get_state(). 
extend() - Extends the piston, if not already extended.
retract() - Retracts the piston, if not already retracted.
toggle() - Puts the piston into the opposite state of its current state.
get_state() - Returns the current state of the piston.
#466
Pneumatics class will help adjust and know the state of the piston.
Test the functions of the class.

✨ PROS 4: Add ADIPneumatics Class

---

include/pros/motors.hpp
src/devices/vdml_motors.cpp

Fixed erase port negative sign functionality
fixed erase port being accessible from motor
closes threads #18 and partially #19 from the beta test.
`pros::Motor_Group` mg({1, -2, 3, -4, 5});
mg.erase_port(2);
mg.erase_port(-1);
mg.erase_port(-3);
mg.erase_port(-4);
mg.get_ports()[0]; //returns 5 as expected
`

🐛PROS 4: fixed erase port

---

common.mk

spaces
Added a wildcard function when the `char const * const _PROS_COMPILE_DIRECTORY` variable is assigned. 
#472 
Tested with
Create a new pros project using `pros c new <project name>`
Create a project name with spaces and a project with parenthesis
Compile and run without any errors

🐛 PROS 4: Prevent paths with parenthesis and spaces from breaking

---

common.mk

space paths from crashing
Added a wildcard function when the char const * const _PROS_COMPILE_DIRECTORY variable is assigned.
#472 
Tested with
Create a new pros project using pros c new "project name"
Create a project name with spaces and a project with parenthesis
Create a project name with both spaces and parenthesis
Compile and run without any errors

🐛 PROS 3.8: Prevent File Paths with Spaces/Parenthesis Causing Error

---

include/vdml/vdml.h
src/devices/vdml.c

This disables (not removes) the logging code that the VDML had. Since PROS 4 no longer shows messages for device disconnects, mismatches, etc. this code is no longer needed. It was not completely removed since we want to add better logging in the future. See #518

💀 PROS 4: Remove dead VDML logging code

---

template-Makefile

🐛 PROS 4: Prevent headers from other libraries from being included in templates.

---

include/pros/adi.hpp

Closes:
#526 
Makes it unambigious by deleting the copy constructor for ADIEncoder. While this is a breaking change this should not really effect many codebases that attempt to do this.  
Does not break ABI for any of these major templates.

:bug: PROS 3.8: ADIEncoder Ambiguous Default Constructor

---

include/pros/motors.hpp
src/devices/vdml_motors.c
src/devices/vdml_motors.cpp
src/main.cpp

Adding following functions to motor groups:
1. get_voltages() - get voltages of all motors
2. get_voltage_limits() - get voltage limits of all motors
3. get_raw_positions() - returns a std::vectorstd::int32_t of the raw encoder positions of a motor group
Also check other motor methods that may need motor group implementations e.g. get_temperatures(), get_powers(), etc.
The users can get the voltages and voltage limits of all the motors at once instead getting voltage of individual motors in the group using the array operator. Also consider other motor methods that need to be implemented for motor groups.
Issue #495

✨ PROS 3.8: Missing Functions for Motor Groups

---

include/pros/motors.h
src/devices/vdml_motors.c

Fixes behavior of move absolute and move relative for motors
New behavior: 
motor_move_absolute does not care about sign of the port as it is absolute movement. 
motor_move_relative with a negative port value should move in the reversed direction if the distance is positive.
PROS 3 behavior is still functional if you use the c api motor_set_reversed and only positive port numbers
Current code does not behave as expected
Test 1:
Test 2:

:bug: PROS 4: Fix Motor Behavior for move_absolute and move_relative

---

include/pros/gps.h
include/pros/gps.hpp
src/devices/vdml_gps.c
src/devices/vdml_gps.cpp

Updated behavior of GPS's `get_offset` to return a struct with offset, added a `get_position` while I was at it to return just the X and Y position. 
Community pointed it out, I was always bothered by how we did this.

🚸 PROS 4: Update behavior of GPS to return a struct with offset, add get_position. 

---

src/devices/vdml_motors.cpp

Motor::set_reversed_all(false) would do nothing, when it was supposed to un reverse a motor. 
Was hardware tested. 
left_mtr = 100;
pros::delay(1000);
left_mtr.set_reversed_all(true);
left_mtr = 100;
pros::delay(1000);
left_mtr.set_reversed_all(false);
left_mtr = 100;```

🐛PROS4 Motor::set_reversed_all(false) fix

---

include/pros/screen.hpp
src/devices/screen.cpp

Summary:
Adds pros::lcd::is_initialized to the weak symbol table for LLEMU stubs. This is a way to help templates who check for this (such as EZTemplate) to see if both LVGL is installed and LLEMU is initialized. To accomplish this, this function will return false if it is still defined as the weak symbol.
Motivation:
Porting work on EZTemplate.
References (optional):
closes https://github.com/purduesigbots/pros/issues/549
Test Plan:

:sparkles: PROS 4: Add LCD Initialize Weak Symbol

---

include/pros/screen.h
include/pros/screen.hpp
src/devices/screen.c
src/devices/screen.cpp

Summary:
added pros::screen::set_pen and set_eraser with a uint32_t as an input since values outside of pros::Color do not work without it.
Motivation:
Template/porting work is a hassle without custom colors, and it would be nice for our users.
References (optional):
closes https://github.com/purduesigbots/pros/issues/548
Test Plan:

✨ PROS 4: Add numerical color override for pen/eraser

---

include/pros/screen.h

Small change to fix centered large text display
Because the macro prevented compilation

:bug: Fixed broken TEXT_LARGE_CENTER macro

---

src/devices/controller.cpp

The `competition` namespace was accidentally in the `pros::v5` namespace, at least inside `controller.cpp`. This was not the case in `misc.hpp`, which lead to linker issues when building user projects. This PR fixes the issue.
This PR was tested by building the kernel and applying it to a new project, with calls to all four of the competition namespace functions:
```cpp
pros::competition::is_autonomous();
pros::competition::is_connected();
pros::competition::is_disabled();
pros::competition::get_status();
```
The project linked without errors.

🐛 PROS 4 - Remove the Competition Namespace From the v5 Namespace

---

include/pros/motor_group.hpp

removes the << operator from motor groups
Calling the << operator on a motor group would cause linking issues
After beta release we can implement it properly
- [] Compiles

🐛Removed operator<< for motor groups

---

src/rtos/stream_buffer.c

Added mutex control to protect printf and cout from causing utf-8 encoding errors due to race conditions. This is done by preventing context switches while prvWriteBytesToBuffer() and prvReadBytesToBuffer() is executing.
BUG: Multiple threads writing to stdout can cause encoding errors #500 
It is difficult to verify that the changes entirely prevents utf-8 encoding errors since the race condition is difficult to reproduce consistently.

🐛Add mutex control for printf and cout

---

include/pros/adi.hpp
src/devices/vdml_adi.cpp

The current design is too complex and buggy. Below is a list of identified anomalies in the Pneumatics class:
Anomaly Category:
**M**issing, **E**xtraneous, **A**mbiguous, **I**nconsistent, **W**rong (incorrect fact), **T**ypos (or editorial), **O**thers
```
Assume get_state get the physical state of the pneumatics
For P = Pneumatics(bool start_extended, bool active_low = false)
extend() -> s = true;
retract() -> s = true; [W1] should be false
toggle() -> s = !s;
get_state() -> false ? state : !state;
^used
[W2] if extend() is used, state should be true and the function returns false
but it is expected to return true as the physical state is true
extend() -> s = false;
retract() -> s = false; [W3] should be true
toggle() -> s = !s;
get_state() -> true ? state : !state;
^used
[W4] if …
```

:recycle: Rewrite ADI Pneumatics class

---

include/pros/link.h
include/pros/link.hpp

Fixed spelling of reciever to receiver
It was a typo
Brought up as an issue in https://github.com/purduesigbots/pros-docs/pull/334
Compiles

🐛PROS4 Fixed spelling of reciever to receiver

---

include/pros/adi.hpp

Removes -Wreorder warnings from pneumatics class

🐛 Pros4/pneumatics member order

---

src/system/newlib_stubs.c

Adds nullchecks to the clock time functions. There weren't nullchecks before.

:bug: Add nullchecks to clock time functions

---

src/devices/vdml_motors.c

Quick bugfix for get_actual_velocity. 
It was freeing the wrong mutex if the port was negative
Bug reported in PROS beta Testing server. 
https://discord.com/channels/1025259843763847229/1137832674506059806/1137832825391947928

Fixed returning the wrong port

---

include/pros/motor_group.hpp

Motor Groups method get_target_velocity() does not have a default index of 0. You should be able to provide no arguments to get_target_velocity() and have it return the target velocity of the first motor in the list (motor @ index 0). 
Every other similar motor group method has the default index set to 0.
Manually Tested

Update default index of get_target_position in motor groups

---

include/pros/motor_group.hpp

The C++ API docs for Motor Groups say "Motors C++ API module" at the top, when it should be "Motor Groups C++ API module"
Correct the typo
N/A

Update Doxygen group definition for motor groups

---

include/pros/motor_group.hpp
include/pros/motors.hpp

Updated text in the motors docs to remove typos
Correct typos

Fix typos in motors/motor groups docs

---

include/pros/rotation.hpp
src/devices/vdml_rotation.cpp

Changed unsigned port parameter in Rotation constructor to signed
Allow for negative port values to reverse their positive port
Generalize negative port = reverse functionality for more classes
#588
Ensure rotation sensor is reversed when a negative port is input, regardless of reverse_flag value.

✨Negative port values for Rotation class

---

src/main.cpp

Updated main.cpp opcontrol to use pros 4 features
Showcase to the users new features of pros 4 and better documentation
Motors respond to control inputs correctly when running opcontrol

♿️Update main.cpp with pros 4 features

---

include/pros/motor_group.hpp
include/pros/motors.hpp
src/devices/vdml_motorgroup.cpp
src/devices/vdml_motors.cpp

Fixes bugs with default constructors. 
Fixes copy constructors. 
adds new set_gearing function for motor groups that takes in vectors of motor groups
Critical bugfixes when constructing multiple motors / motor groups.
Adds a feature request for motor groups.

Motor bug fixes and add new set_gearing

---

include/pros/adi.hpp
src/devices/vdml_adi.cpp
src/devices/vdml_ext_adi.c

Added a get_port() method for all adi sesnors with functionality for adi extenders
Requested feature.

:sparkles: ADI Get Port

---

src/devices/vdml_rotation.cpp

Fixed the rotation sensor not working when initialized with a negative port number
The rotation sensor currently does not work when using a negative port number to reverse it during initialization

🐛Fix Negative Port Rotation Sensor

---

src/system/dev/vfs.c

Allows for open for the sd card to no longer need paths to start with "/usd/" UNLESS the path begins with "usd", "dev", or "ser".
TO access those folders you still need the usd prefix as before. 
Some examples: 
if there is a file called a.txt in the main folder of the sd card, it can be accessed via a path of "/usd/a.txt" or "a.txt" would work.
However, if there is a file called b.txt in a folder called dev, it must be accessed via the path of "/usd/dev/b.txt"
Makes file IO via the SD card way easier for users

✨Allows for file open to default to the sd card.

---

include/pros/imu.h
src/devices/vdml_imu.cpp
src/main.cpp

Fixed Imu::is_calibrating function to return correct values.
Users can use this function to properly check if their connected imu is calibrating or not, and also get the proper return value of false if they call this function on an imu that is not connected.

🐛Fixed Imu::is_calibrating function for PROS 3 #626

---

src/devices/vdml_ext_adi.c

ADI zero indexing fixes for pros 3
Include ADI mutex fixes onto pros 3
#631 #633

🐛ADI mutex fix for pros 3

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
include/pros/gps.h
include/pros/gps.hpp
include/pros/imu.h
src/devices/vdml_ext_adi.c
src/devices/vdml_gps.c
src/devices/vdml_gps.cpp
src/devices/vdml_imu.cpp

[🐛ADI mutex fix for pros 3 (](https://github.com/purduesigbots/pros/commit/eec7d25188e5076ca70a3e16f4cf4c57ce79836d)https://github.com/purduesigbots/pros/pull/636[)](https://github.com/purduesigbots/pros/commit/eec7d25188e5076ca70a3e16f4cf4c57ce79836d)
[✨ Add to GPS API (](https://github.com/purduesigbots/pros/commit/4aa077d81cb317967434f2611ce2513063a84944)https://github.com/purduesigbots/pros/pull/630[)](https://github.com/purduesigbots/pros/commit/4aa077d81cb317967434f2611ce2513063a84944)
[🐛Fixed Imu::is_calibrating function for PROS 3](https://github.com/purduesigbots/pros/commit/dbb45996a1b029b86f50bbf81a5ca2de6a6fb496) https://github.com/purduesigbots/pros/issues/626 [(](https://github.com/purduesigbots/pros/commit/dbb45996a1b029b86f50bbf81a5ca2de6a6fb496)https://github.com/purduesig …

🔀Release Candidate 3.8.2

---

include/pros/gps.hpp

Fix gps comments
<br>
Add periods to separate two sentences shown in PROS 4 doc. And, change "an" GPS to "a" GPS .

🐛Fix gps comments

---

include/pros/imu.h
include/pros/imu.hpp
src/devices/vdml_imu.c
src/devices/vdml_imu.cpp

Fixes the issues with the IMU reset never returning
Adds functionality to get the Orientation of the IMU
Currently on pros 3.8.2 IMU can only calibrate in the Z_DOWN orientation. The reset function is an infinite loop otherwise. 
Adds functionality to get the Physical Orientation of the IMU.

🐛Imu Reset bugfix and IMU get orientation

---

src/devices/vdml_motors.c

This fixes an issue where a port mutex was not returned when calling `motor_get_voltage_limit`.  
Calling `motor_get_voltage_limit` on a port that has a motor plugged in would break any subsequent motor functions on that port as well as the serial terminal.

🐛Fix motor voltage limit port mutex returning
