purduesigbots/pros

- README.md
Well I thought I could use the existing branch. I thought wrong. @edjubuh fix it 😢
> fix site link too

- README.md
I swear this better be the last time I do this.
Also I deserve credit because I did this all from my phone.
> fix links in readme (#23)

- README.md
> add discord invite link

- .gitignore
- Makefile
- common.mk
- include/API.h
- include/comm.h
- include/fs.h
- src/comm.c
- src/fs.c
- src/printf.c
- template/Makefile
- template/common.mk
Release notes:
- **NOTE: standalone mode was merged into master in 0e4cd5948bdc68e9cf0f8e8921b399b541b22e4c**
- Add standalone mode. Call `standaloneModeEnable()` during `initializeIO()`.
- Rename FILE to PROS_FILE to improve C++ compatibility. Existing code does not need to change
- Use PROS CLI as default for `make upload`. To use the legacy upload.jar, run `make upload-legacy`
> 2.12.0 - C++ FILE Compatibility

- src/malloc.c
Implemented void* calloc(size_t num, size_t size)
> Implemented calloc

- Jenkinsfile
- Makefile
- build.sh
Simplifies Jenkinsfile in our effort to reduce complexity requirements of Jenkins
> Work with EVN Jenkins instance

- README.md
> Clarify that PROS 2 doesn't support c++

- include/kernel.h
> bump version listed in kernel.h to latest

- README.md
- azure-pipelines.yml
Add Azure Pipelines for building templates
It'd be nice to have standard CI builds of the kernel
> 👷‍♂️ Add Azure Pipelines for building templates

- src/devices/vdml_motors.c
Someone forgot to check the port number. It should 0-based numbering.
Love? Maybe...
closes #161;  #160
> 🐛 Fix motor PID functions bug

- include/display/lv_conf.h
does what it says on the tin
someone asked for it
closes #194
> ✨ Enable LVGL keyboard

- include/pros/adi.h
- include/pros/adi.hpp
Ports were labelled wrong in the header file documentation for ultrasonic sensors
wrong things are bad
closes #196 
header only
> 💡 Fix ultrasonic docs

- src/system/dev/file_system_stubs.c
> backmerge release branch onto develop

- include/pros/apix.h
- src/display/display.c
- src/system/startup.c
I was looking at issue #168. The second step is to rework kernel initialization.
Because step 1 is skipped :see_no_evil:
#168 
Please help me to compile the kernel for test
> ✨ Multiple phases of initialization

- include/pros/apix.h
- src/display/display.c
- src/system/startup.c
This reverts commit f65dd4731d25f78380afed60ba82842098b7c1a0.
Revert ✨ Multiple phases of initialization
> Revert "✨ Multiple phases of initialization (#209)"

- include/pros/apix.h
Fixed a documentation comment for queue_recv
> Fixed queue_recv doc comment

- include/pros/apix.h
Fix a wrong comment in queue_append
Spotted while looking at #238
> Fix another comment

- include/api.h
- include/pros/adi.hpp
- include/pros/apix.h
- include/pros/ext_adi.h
- include/pros/rtos.h
- include/pros/rtos.hpp
- include/vdml/port.h
- src/devices/controller.c
- src/devices/vdml_adi.c
- src/devices/vdml_adi.cpp
- src/devices/vdml_ext_adi.c
- src/display/display.c
- src/rtos/rtos.cpp
- src/rtos/semphr.c
- src/system/startup.c
- src/tests/ext_adi.cpp
> Merge Develop into Remove IMU Check

- azure-pipelines.yml
Changed instance of pros-cli-v5 to pros-cli to reflect changes in cli repo.
> 🚸Change pros-cli-v5 to pros-cli

- include/pros/rotation.h
- include/pros/rotation.hpp
- src/devices/vdml_rotation.c
- src/devices/vdml_rotation.cpp
Adds new data rate set functions for rotation sensor
> ✨ Added rotation data rate function

- src/devices/vdml_distance.c
- src/devices/vdml_distance.cpp
- src/devices/vdml_optical.c
- src/devices/vdml_optical.cpp
Stop it
Send helps
#257 #259 
uh
> :memo: Fix file headers typo

- include/pros/motors.h
- include/pros/motors.hpp
- src/devices/vdml_motors.c
- src/devices/vdml_motors.cpp
Adds a function to set the motor voltage to zero.
There isn't already a motor stop function
Make motor run and use function to stop motor
> ✨Add motor stop function

- README.md
Updated atom link to VS code link in README
Fixes #370
> Updated README Link

- src/devices/vdml_imu.c
Replace if checks with Modulo to improve readability where applicable. 
Closes #371
> 🎨Update vdml_imu to Use Modulo

- azure-pipelines.yml
Update to latest version of toolchain and cli
> Update CI Toolchain and CLI

- include/pros/colors.h
Was doing a logical and instead of bitwise and.
> 🐛Fix issue with color2g

- include/pros/motors.hpp
- src/devices/vdml_motors.cpp
Adds get_gearing methods and set_brake_modes for motor groups
Fixes style issues on vdml_motors.cpp and motors.hpp
Missing features from the initial Motor groups PR
> ✨Add Missing Features to Motor Groups

- include/pros/motors.hpp
Added one line that hopefully does what it is meant to do
Was my first project
Try using MotorGroup and see if it functions as Motor_Group
> ✨Add MotorGroup alias for Motor_Group

- src/devices/vdml_adi.cpp
Says what it does
See if this was an issue in the first place with effected functions, and then see if this PR changes anything.
> 🐛 Add ext_ to missing CPP functions for adi C++ 

- azure-pipelines.yml
Fix Azure Pipelines Python version so that the CI builds
ranch suace
Make sure CI builds kernel.
> 🐛 Fix Azure Pipelines Python version so that the CI builds

- azure-pipelines.yml
> 🐛 Fix Azure Pipelines Python version

- include/pros/motors.hpp
- src/devices/vdml_motors.cpp
Reverts purduesigbots/pros#468
> Revert "✨ PROS 4: Motor '=' Operator Copy Constructor"

- include/pros/motors.h
- include/pros/motors.hpp
- src/devices/vdml_motors.c
- src/devices/vdml_motors.cpp
Not too useful, should be removed to reduce time and space complexity.
> :fire: PROS 4: Remove Pure Color Calls from Motors

- include/pros/motors.hpp
- src/devices/vdml_motors.cpp
Added get_temperature to motor groups.
> :sparkles: Added get_temperature to motor groups. 

- include/pros/motors.h
- src/devices/vdml_motors.c
Changes motor_move_absolute to care about the sign of the motor
> 🐛Pros4/bugfix/move absolute v2

- src/devices/vdml_motors.c
Adjusted implementation of getters and a variety of methods to be more inline with expected behavior
```
motor_move_relative(-1, 100, 100); // Moves 100 units forward
while (!((motor_get_position(-1) < 105) && (motor_get_position(-1) > 95))) {
// Continue running this loop as long as the motor is not within +-5 units of its goal
delay(2);
}
motor_move_relative(-1, 100, 100); // Also moves 100 units forward
while (!((motor_get_position(-1) < 205) && (motor_get_position(-1) > 195))) {
delay(2);
}
}
```
> 🐛PROS 4 negative port support in C API

- include/pros/abstract_motor.hpp
- include/pros/imu.hpp
- include/pros/motor_group.hpp
- include/pros/motors.hpp
- src/devices/vdml_imu.cpp
- src/devices/vdml_motorgroup.cpp
- src/devices/vdml_motors.cpp
Change enum classes in motor related files and Imu_status to PascalCase.
Change requested by user and improves code cleanliness.
PROS 4: Update structure/class/enum case sytles #556
> :sparkles: PROS 4: Change Motors and Imu enum classes to PascalCase

- README.md
I fixed two misspelled words in the project's README.
Words should be spelled correctly.
> Correct misspelled word

- include/pros/misc.h
- include/pros/misc.hpp
- src/devices/vdml_usd.c
- src/devices/vdml_usd.cpp
Adds functionality to list the files on a sd card
Frequently requested feature. I will add a new issue to provide a wrapper function for the CPP api to overload it to return a list of strings without the user only needing to give the path
> ✨Add list_files function

- src/system/dev/usd_driver.c
Currently working on an fflush for files on an sd card to be integrated into standard IO; however, this modifies the write function to flush the buffer when writing to a file.
No working fflush adjacent function for file IO on the sd card currently.
> Fflush on write
